clean-up

diff --git a/verify-cli-bash/verify b/verify-cli-bash/verify
--- a/verify-cli-bash/verify
+++ b/verify-cli-bash/verify
@@ -1,29 +1,29 @@
 #!/bin/bash
 
-# Parse the command-line arguments
-while getopts ":ear:t:" opt; do
+default_diff_tool="code --diff"
+diff_tool=$default_diff_tool
+
+while getopts ":r:t:d:" opt; do
   case $opt in
-    r) received_text="$OPTARG";;
-    e) echo_flag=true;;
-    a) echo_flag=true;;
-    t) test_name="$OPTARG";;
+    d) diff_tool=$OPTARG;;
+    r) received_text=$OPTARG;;
+    t) test_name=$OPTARG;;
     \?) echo "Invalid option: -$OPTARG" >&2;;
   esac
 done
 
-# Read standard input without a delimiter
-if [ "$received_text" == "" ]; then
-    while read -r line; do
-    input="$input$line"
-    done
+received=$test_name.received
+approved=$test_name.approved
+
+if [ "$received_text" == "" ];
+then
+    cat - > $received
+else
+    echo $received_text > $received
 fi
 
-# Print the input unless the --no-echo flag was passed
-if [ "$echo_flag" == true ]; then
-  echo "input: $input"
-fi
+touch $approved
 
-# Print the test name if the -t flag was passed and the -a flag was not passed
-if [ "$test_name" != "" ] && [ "$echo_flag" == true ]; then
-  echo "test: $test_name"
-fi
+diff $received $approved > /dev/null \
+    && (echo "test passed"; rm $received) \
+    || (echo "test failed"; eval "$diff_tool '$received' '$approved'")
