! F Add emojis to verify
Co-authored-by: Matt Wynne <matt@mattwynne.net>
Co-authored-by: Jacqueline Lee <jmasonlee@gmail.com>

diff --git a/utils/verify b/utils/verify
--- a/utils/verify
+++ b/utils/verify
@@ -5,25 +5,31 @@ diff_tool=$default_diff_tool
 
 while getopts ":r:t:d:" opt; do
   case $opt in
-    d) diff_tool=$OPTARG;;
-    r) received_text=$OPTARG;;
-    t) test_name=$OPTARG;;
-    \?) echo "Invalid option: -$OPTARG" >&2;;
+  d) diff_tool=$OPTARG ;;
+  r) received_text=$OPTARG ;;
+  t) test_name=$OPTARG ;;
+  \?) echo "Invalid option: -$OPTARG" >&2 ;;
   esac
 done
 
 received="$test_name.received"
 approved="$test_name.approved"
 
-if [ "$received_text" == "" ];
-then
-    cat - > "$received"
+if [ "$received_text" == "" ]; then
+  cat - >"$received"
 else
-    echo "$received_text" > "$received"
+  echo "$received_text" >"$received"
 fi
 
 touch "$approved"
 
-diff -q "$received" "$approved" > /dev/null \
-    && (echo "test passed"; rm "$received") \
-    || (echo "test failed"; $diff_tool "$received" "$approved" </dev/tty; false)
+diff -q "$received" "$approved" >/dev/null &&
+  (
+    echo "✅ test passed"
+    rm "$received"
+  ) ||
+  (
+    echo "❌ test failed"
+    $diff_tool "$received" "$approved" </dev/tty
+    false
+  )
