e measure time, cli flag -4, log to stderr

diff --git a/utils/verify b/utils/verify
--- a/utils/verify
+++ b/utils/verify
@@ -25,11 +25,11 @@ touch "$approved"
 
 diff -q "$received" "$approved" >/dev/null &&
   (
-    echo "✅ test passed"
+    echo "✅ test passed" >&2
     rm "$received"
   ) ||
   (
-    echo "❌ test failed"
+    echo "❌ test failed" >&2
     $diff_tool "$received" "$approved" </dev/tty
     false
   )
