git add all the things

diff --git a/utils/verify b/utils/verify
--- a/utils/verify
+++ b/utils/verify
@@ -1,35 +1,35 @@
-#!/bin/bash
+#!/bin/bash -i
 
 default_diff_tool="code --diff"
 diff_tool=$default_diff_tool
 
 while getopts ":r:t:d:" opt; do
-  case $opt in
-  d) diff_tool=$OPTARG ;;
-  r) received_text=$OPTARG ;;
-  t) test_name=$OPTARG ;;
-  \?) echo "Invalid option: -$OPTARG" >&2 ;;
-  esac
+    case $opt in
+    d) diff_tool=$OPTARG ;;
+    r) received_text=$OPTARG ;;
+    t) test_name=$OPTARG ;;
+    \?) echo "Invalid option: -$OPTARG" >&2 ;;
+    esac
 done
 
 received="$test_name.received"
 approved="$test_name.approved"
 
 if [ "$received_text" == "" ]; then
-  cat - >"$received"
+    cat - >"$received"
 else
-  echo "$received_text" >"$received"
+    echo "$received_text" >"$received"
 fi
 
 touch "$approved"
 
 diff -q "$received" "$approved" >/dev/null &&
-  (
-    echo "✅ test passed" >&2
-    rm "$received"
-  ) ||
-  (
-    echo "❌ test failed" >&2
-    $diff_tool "$received" "$approved" </dev/tty
-    false
-  )
+    (
+        echo "✅ test passed" >&2
+        rm "$received"
+    ) ||
+    (
+        echo "❌ test failed" >&2
+        $diff_tool "$received" "$approved" </dev/tty
+        false
+    )
